export type ModelPricing = {
  readonly input: number
  readonly output: number
  readonly cacheRead?: number
  readonly cacheWrite?: number
}

export type PricingSnapshot = {
  readonly source: "models.dev"
  readonly sourceUrl: "https://models.dev/api.json"
  readonly generatedAt: string
  readonly providers: Readonly<Record<string, Readonly<Record<string, ModelPricing>>>>
}

const MODELS_DEV_SOURCE = "models.dev" as const
export const MODELS_DEV_SOURCE_URL = "https://models.dev/api.json" as const

type ModelsDevProviderModel = {
  readonly cost?: {
    readonly input?: number
    readonly output?: number
    readonly cache_read?: number
    readonly cache_write?: number
  }
}

type ModelsDevProvider = {
  readonly models?: Readonly<Record<string, ModelsDevProviderModel>>
}

type ModelsDevApiResponse = Readonly<Record<string, ModelsDevProvider>>

const isFiniteNumber = (value: unknown): value is number => typeof value === "number" && Number.isFinite(value)

const normalizeModelPricing = (model: ModelsDevProviderModel): ModelPricing | undefined => {
  const cost = model.cost
  if (!cost || !isFiniteNumber(cost.input) || !isFiniteNumber(cost.output)) {
    return undefined
  }

  return {
    input: cost.input,
    output: cost.output,
    ...(isFiniteNumber(cost.cache_read) ? { cacheRead: cost.cache_read } : {}),
    ...(isFiniteNumber(cost.cache_write) ? { cacheWrite: cost.cache_write } : {}),
  }
}

/**
 * Reduce the provider-keyed `models.dev` payload to the compact pricing-only
 * snapshot that `open-azdo` vendors in-repo. Providers and models are sorted
 * to keep generated diffs deterministic.
 */
export const normalizeModelsDevPricingSnapshot = (
  response: ModelsDevApiResponse,
  generatedAt: string,
): PricingSnapshot => {
  const providers = Object.fromEntries(
    Object.entries(response)
      .map(([providerID, provider]) => {
        const models = Object.fromEntries(
          Object.entries(provider.models ?? {})
            .sort(([left], [right]) => left.localeCompare(right))
            .flatMap(([modelID, model]) => {
              const pricing = normalizeModelPricing(model)
              return pricing ? ([[modelID, pricing]] as const) : []
            }),
        )

        return [providerID, models] as const
      })
      .filter(([, models]) => Object.keys(models).length > 0)
      .sort(([left], [right]) => left.localeCompare(right)),
  )

  return {
    source: MODELS_DEV_SOURCE,
    sourceUrl: MODELS_DEV_SOURCE_URL,
    generatedAt,
    providers,
  }
}

/**
 * Render the vendored snapshot as a stable TypeScript module so the generated
 * file can be checked into the repo and imported synchronously at runtime.
 */
export const renderModelsDevPricingSnapshotModule = (snapshot: PricingSnapshot) =>
  [
    'import type { PricingSnapshot } from "../internal/ModelsDevPricingSnapshot"',
    "",
    "// Generated by `bun run sync:model-pricing`. Do not edit by hand.",
    `export const modelsDevPricingSnapshot: PricingSnapshot = ${JSON.stringify(snapshot, null, 2)} as const`,
    "",
  ].join("\n")
